version: '3'

services:
  mongodb:
    container_name: chat-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=shhh
    volumes:
      - mongodb_data_container:/data/db

  localstack:
    container_name: chat-localstack
    image: localstack/localstack
    environment:
      - HOSTNAME_EXTERNAL=localstack
      - SERVICES=sqs:4576
    ports:
      - "4576:4576"

volumes:
  mongodb_data_container: