version: '3'

services:
  mongodb:
    container_name: chat-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=shhh
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: